### ISSUE TITLE
Error when building index with a large input file

### ISSUE THREAD

**Issue by AllanCAguiar** [jermp/autocomplete#10]
I am encountering an error when attempting to execute this code with a proprietary collection of queries. The collection has 23 million lines, but the same error occurs with a reduced version containing 80 thousand lines. I am only able to execute it with 78 thousand lines or fewer.

This is the output:
80000
2023-08-14 11:48:12: building completion_trie...
2023-08-14 11:48:12: DONE
2023-08-14 11:48:12: building fc_dictionary with bucket size 16...
7.46464 characters per string
2023-08-14 11:48:12: DONE
2023-08-14 11:48:12: building inverted_index...
avg. list size = 14.4693
max_list_size = 33817
min_list_size = 1
2023-08-14 11:48:12: DONE
2023-08-14 11:48:12: building forward_index...
using 86788 words
2023-08-14 11:48:12: DONE
2023-08-14 11:48:12: building unsorted_list...
	using 17 [bpi]
2023-08-14 11:48:12: DONE
2023-08-14 11:48:12: building minimal_docids...
	using 17 [bpi]
2023-08-14 11:48:12: DONE
terminate called after throwing an instance of 'std::runtime_error'
  what():  sequence is not sorted.
Aborted (core dumped)

**Comment by AllanCAguiar** [comment]
This is what I am doing step by step:
1. Cloning the repository with "git clone --recursive https://github.com/jermp/autocomplete.git"
2. Adding "#define DOCTEST_CONFIG_NO_POSIX_SIGNALS" to test/test_common.hpp(An error occurs on Linux when compiling doctest.h without this flag)
3. Making build with:
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_SANITIZERS=Off -DUSE_INTRINSICS=On -DUSE_PDEP=On
make -j

Those warnings appears:
warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 9513 |     snprintf(path, sizeof(path), "%s/%s", opts->document_root, file_name);
      |                                        ^
In file included from /usr/include/stdio.h:894,
                 from /home/allan/Documents/autocomplete/external/mongoose/mongoose.h:409,
                 from /home/allan/Documents/autocomplete/external/mongoose/mongoose.c:1:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: ‘__builtin___snprintf_chk’ output 2 or more bytes (assuming 4097) into a destination of size 4096
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~

4. Go to test_data, update python to python2 in the preprocessing.sh file, create a folder named sample, place the sample.completions file inside it, and then execute "bash preprocess.sh sample/sample.completions 1000"
5. Go to build and try to build the index with "./build ef_type1 ../test_data/sample/sample.completions -o sample.ef_type1.bin"
Then the error occurs.

This don't happens when the collection have 78k lines or with the trec05 collection. 

The minimal dataset:
[sample.txt](https://github.com/jermp/autocomplete/files/12480208/sample.txt)

**Comment by jermp** [comment]
Ok thanks, received.
I'm abroad at the moment so I cannot investigate right now, but surely will do next week.

Best,
-Giulio

**Comment by AllanCAguiar** [comment]
Hello, how's it going? If needed, I can provide other datasets or help with troubleshooting the issue

**Comment by jermp** [comment]
Hi @AllanCAguiar, and sorry for not being in touch but it's a very busy period here.
I'm trying to reproduce the error. Will let you know.

Best,
-Giulio

**Comment by jermp** [comment]
Ok, yes, I confirm I can reproduce the error on my end. I'll do some experiments and get back to you asap.
Best,
-Giulio

**Comment by jermp** [comment]
Ok, found! The problem is not related to my code. You have an extra space in your completions file, here:

    79352 acao trabalhista  servidor publico estadual

which causes the completions to not lexicographically sorted.
So, just remove that space and resort the completions and it works.

Here is the "clean" file: [sample.clean.completions.gz](https://github.com/jermp/autocomplete/files/12706605/sample.clean.completions.gz).

Best,
-Giulio

**Comment by AllanCAguiar** [comment]
Wow, thanks. I adjusted to this formatting, and now it's working with the entire dataset. I appreciate your time and attention to find the error.

**Comment by AllanCAguiar** [comment]
One more thing, could you please remove the adjusted file in your comment?
Since it's a private dataset and cannot be left public

Em sáb., 23 de set. de 2023 às 09:58, Giulio Ermanno Pibiri <
***@***.***> escreveu:

**Comment by jermp** [comment]
> Wow, thanks. I adjusted to this formatting, and now it's working with the entire dataset. I appreciate your time and attention to find the error.

You're welcome! If you use this codebase, please cite our SIGIR paper.

 > One more thing, could you please remove the adjusted file in your comment?
Since it's a private dataset and cannot be left public.

Of course, done it!

Let me know if I can further assist you.

Best,
-Giulio
